### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by dandyxu** [thebrandonallen/bp-block-users#1]
Hi, Brandon
      Thanks for your plugin. The ideas of your bp-block-users for specific time period are exactly what I want. <br />But, when I tried your plugin in my site, I found that it cannot block specific user role in specific time period. I'm using the latest WordPress 4.4.1 and BuddyPress 2.4.3. <br />Could you check that for me? Thanks a million.

**Comment by thebrandonallen** [comment]
Correct, it doesn't block based on role. This only works at the individual user level.
