### ISSUE TITLE
Translation does not work to all fields and false linking

### ISSUE THREAD

**Issue by per4mance** [thebrandonallen/bp-block-users#11]
Hi,
I translated the pot file into German but unfortunately 90% shows still the English version. Second found out that the link to menu 'Block user' is linked to the own profile and not to the profile I'm watching. See the attached screenshots.

Would be great to check the connections of your great plugin. Use v1.0.1.

Kindest regartds,
Thorsten
![01-09-_2017_21-49-58](https://user-images.githubusercontent.com/3984555/29991681-f14a6570-8f61-11e7-8cd6-74f34d32bf4d.jpg)

![01-09-_2017_21-58-13](https://user-images.githubusercontent.com/3984555/29991675-bb3d6c52-8f61-11e7-93dd-707fbf3b98f9.jpg)

**Comment by thebrandonallen** [comment]
I'll have to look into the menu issue.

As far as the translations, where are you putting your translation file? The plugin expects your file to be in `wp-content/languages/plugins`, then it also needs to be properly named. In your case it's likely `bp-block-users-DE_de.mo`.

**Comment by per4mance** [comment]
Ok you're right I missed the right folder. I put the files into `wp-content/plugins/bp-block-users/languages` Now I changed and it works but I have still the issue of false linking, see attached screenshot. From the menu where I'm logged in as admin, it shows my username to the profile I`m watching.
![03-09-_2017_08-42-17](https://user-images.githubusercontent.com/3984555/30002631-947fb420-9084-11e7-8cdc-f086aeff0867.jpg)

**Comment by thebrandonallen** [comment]
Yeah, like I said above, I'll have to look into the menu issue when I get some time.

**Comment by thebrandonallen** [comment]
Fixed in #13
