### ISSUE TITLE
0.2 Ready for use?

### ISSUE THREAD

**Issue by greggh** [thebrandonallen/bp-block-users#5]
I am just wondering about using this plugin, it looks like you're saying 0.1.0 shouldn't be used, and I should be using 0.2.0. Any idea when 0.2.0 will be pushed to wordpress.org?  Is it ready for testing now? Can I just grab a zip of the repo here and go?

**Comment by thebrandonallen** [comment]
The short answer to all your questions is "no."

Not sure where you got the impression that 0.1.0 _shouldn't_ be used, but that's definitely not the case. There is nothing wrong with 0.1.0. The majority of the underlying code of 0.1.0 is still in 0.2.0. It's just probably under a different name.

I'm still breaking things on 0.2.0, and it's also not, currently, backwards compatible, so I wouldn't use it. If you'd like to test on a test server, you are welcome to do that, but I wouldn't run it on a production server. That's not to say it's unstable. It's just that I'm only going to write an upgrade path for 0.1.0 -> 0.2.0. Not one for something I wrote a couple of weeks ago, that I've changed my mind on this week.

As far as when it's going to be pushed to 0.2.0. No clue. It'll be pushed when it's finished 😄

**Comment by greggh** [comment]
Thanks for the quick response. I must have just misread things. It's been a long he testing side, I don't have a live site yet. This is a new build so I am hunting down the tools I might need to run this thing with a large community. This plugin just stands out as something I am going to need.

I'll use 0.1.0 for now and eagerly await 0.2.0

**Comment by thebrandonallen** [comment]
My hope is to have 0.2.0 out the door soon, but we'll see.
